# Generated by Django 4.2.6 on 2023-12-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_position_options_alter_position_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товар магазина'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='gramm',
        ),
        migrations.RemoveField(
            model_name='position',
            name='sostav',
        ),
        migrations.AlterField(
            model_name='position',
            name='price',
            field=models.IntegerField(max_length=7, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.CharField(max_length=40, verbose_name='Производитель'),
        ),
    ]
